name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install npm packages
        run: npm ci
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Run examples
        run: |
          node examples/parsing/main.js
          node examples/visit/main.js
