name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node
      - name: Install npm packages
        run: npm i
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Run examples
        run: |
          node examples/parsing/main.js
          node examples/visit/main.js
